### ISSUE TITLE
A Link error

### ISSUE THREAD

**Issue by ghost** [wangkuiyi/mapreduce-lite#1]
按照文档安装了需要的库，编译链接时出现错误：

Linking CXX static library libmapreduce_lite.a
[ 85%] Built target mapreduce_lite
Scanning dependencies of target protofile_test
[ 87%] Building CXX object src/mapreduce_lite/CMakeFiles/protofile_test.dir/protofile_test.cc.o
Linking CXX executable protofile_test
/usr/bin/ld: cannot find -lboost_thread-mt
../gtest/libgtest.a(gtest-all.cc.o)：在函数‘testing::internal::StreamingListener::SocketWriter::MakeConnection()’中：
gtest-all.cc:(.text+0x6fe4): 警告： Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

**Comment by wangkuiyi** [comment]
Can you find libboost_thread*.a somewhere in your system? Is that file named libboost_thread-mt.a or libboost_thread.a?

**Comment by ghost** [comment]
I built it successfully by using the code on Google code. But failed on github. I think there is e mistake in CMakefile.txt of github version.  :)

**Comment by wangkuiyi** [comment]
I see. There is a difference between CMakelist in these two repositories -- the Github version requires users to modify the CMakelist file to specify to where boost, gflags and libevent were installed. This allows users to install these thirdparty libraries using package management tools as well as from source code. Whereas the Google Code version assumes that you install thirdparty libraries to prespecified directory.

**Comment by abigbigbird** [comment]
How can i resolve it by using the github's code? BTW, where is the code on Google code, have a address please, thx!
